### PR TITLE
Swift 2

### PR DESCRIPTION
**Pull request by greg3z**
It's not a re-write in a pure Swift 2 style, but at least it compiles and runs.

### CODE REVIEW

**Comment by sashakid** [comment]
Hi, as I see, repo owner gave up this project and all pull requests are not committed into the master? I thought I could fix project by myself but there is a lot of code and a lot of errors to fix it to standards of swift 2 etc :-(

**Comment by greg3z** [comment]
You can try my fork : https://github.com/greg3z/VIPER-SWIFT

**Comment by sashakid** [comment]
@greg3z thanks!

**Comment by sashakid** [comment]
@greg3z thanks!

**Comment by JeffGilbert-MM** [comment]
The project has been updated for Swift 2.2/Xcode 7.3 via https://github.com/mutualmobile/VIPER-SWIFT/pull/15.

**Pull request closed without merging**
